{
 "title": "[compact-block] Requested transactions stats",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "per_time",
    "query": "10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Size of requested transactions per $per_time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host) (increase(peerobserver_log_compact_block_reconstruction_requested_bytes[$__interval]))\r\n  and\r\nsum by (host) (changes(peerobserver_log_compact_block_reconstruction_count[$__interval])) > 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Number of requested transactions per $per_time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (host) (increase(peerobserver_log_compact_block_reconstruction_txs_requested[$__interval]))\r\n  and\r\nsum by (host) (changes(peerobserver_log_compact_block_reconstruction_count[$__interval])) > 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Number of transactions in extra pool per $per_time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (host) (increase(peerobserver_log_compact_block_reconstruction_txs_extra_pool[$__interval]))\r\n  and\r\nsum by (host) (changes(peerobserver_log_compact_block_reconstruction_count[$__interval])) > 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Size of requested transactions (without zeroes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host) (peerobserver_log_compact_block_reconstruction_requested_bytes) > 0\r\n  and\r\nsum by (host) (changes(peerobserver_log_compact_block_reconstruction_count[$__interval])) > 0",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "avg_over_time(\r\n  (\r\n    sum by (host) (peerobserver_log_compact_block_reconstruction_requested_bytes) > 0\r\n      and\r\n    sum by (host) (changes(peerobserver_log_compact_block_reconstruction_count[$__interval])) > 0\r\n  )[$per_time:]\r\n)",
     "legendFormat": "{{host}} avg $per_time"
    },
    {
     "expr": "max(peerobserver_validation_block_connected_latest_height) by (host) > 0",
     "legendFormat": "{{host}} height"
    }
   ]
  },
  {
   "title": "Aggregated size of requested transactions  (without zeroes)",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host) (peerobserver_log_compact_block_reconstruction_requested_bytes) > 0\r\n  and\r\nsum by (host) (changes(peerobserver_log_compact_block_reconstruction_count[$__interval])) > 0",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}