{
 "title": "[connections] inbound connection anomaly detection",
 "tags": [
  "big-playlist",
  "connections"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "inbound connection per host",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "peerobserver_conn_inbound_current",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "inbound connection anomaly detection (combined; z-score) ",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(\n(\n  avg_over_time(peerobserver_conn_inbound_current[$__rate_interval])\n  -\n  avg_over_time(peerobserver_conn_inbound_current[2d])\n)\n/\nstddev_over_time(peerobserver_conn_inbound_current[2d])\n)\n",
     "legendFormat": "z-score"
    }
   ]
  },
  {
   "title": "inbound connection anomaly detection (individual nodes; mod-zscore)",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(\n(\n  max_over_time(peerobserver_conn_inbound_current[$__rate_interval])\n  -\n  avg_over_time(peerobserver_conn_inbound_current[10h])\n)\n/\nquantile_over_time(0.5, peerobserver_conn_inbound_current[10h]) \n)\n",
     "legendFormat": "Mod z-score"
    }
   ]
  }
 ]
}