{
 "title": "[invs] INV size and rate",
 "tags": [
  "big-playlist",
  "tx-relay"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "inv size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(peerobserver_p2pextractor_invs_size[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "rate of WTx items in INV messages per second (averaged over $__interval)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(peerobserver_p2pextractor_invs_items{inv_type=\"WTx\"}[$__interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "INV rate per second ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(peerobserver_p2pextractor_invs_messages[10m])",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}