syntax = "proto2";

package log_extractor;

enum LogLevel {
    INFO = 0;      // no bracket
    WARNING = 1;   // [warning] bracket
    ERROR = 2;     // [error] bracket
    DEBUG = 3;     // [category] bracket
    TRACE = 4;     // [category:trace] bracket
}

message log {
  required uint64 log_timestamp = 1; // unix timestamp in microseconds
  required LogDebugCategory category = 2;
  required string threadname = 3;
  required LogLevel log_level = 7;
  required uint64 log_line_bytes = 8;
  oneof log_event {
    UnknownLogMessage unknown_log_message = 4;
    BlockConnectedLog block_connected_log = 5;
    BlockCheckedLog block_checked_log = 6;
    SawNewHeaderLog saw_new_header_log = 9;
    CompactBlockReconstructedLog compact_block_reconstructed_log = 10;
  }
}

// Follows LogFlags in logging.h
enum LogDebugCategory {
    UNKNOWN = 0;
    ADDRMAN = 1;
    BENCH = 2;
    BLOCKSTORAGE = 3;
    CMPCTBLOCK = 4;
    COINDB = 5;
    ESTIMATEFEE = 6;
    HTTP = 7;
    I2P = 8;
    IPC = 9;
    LEVELDB = 10;
    LIBEVENT = 11;
    MEMPOOL = 12;
    MEMPOOLREJ = 13;
    NET = 14;
    PROXY = 15;
    PRUNE = 16;
    QT = 17;
    RAND = 18;
    REINDEX = 19;
    RPC = 20;
    SCAN = 21;
    SELECTCOINS = 22;
    TOR = 23;
    TXPACKAGES = 24;
    TXRECONCILIATION = 25;
    VALIDATION = 26;
    WALLETDB = 27;
    ZMQ = 28;
}

// A log message that does not match any known format.
message UnknownLogMessage {
  required string raw_message = 1; // Raw log message.
}

// 2025-09-27T01:52:01Z [validation] Enqueuing BlockConnected: block hash=41109f31c8ca4d8683ab5571ba462292ddb8486dee6ecd2e62901accc7952f0b block height=437
message BlockConnectedLog {
  required string block_hash = 1;
  required uint32 block_height = 2;
}

// 2025-10-28T02:20:12Z [validation] BlockChecked: block hash=1811952798ccd2ad1264b064c3da6313fba7497159b999ee045afb046c7d0232 state=bad-txns-duplicate, duplicate transaction
message BlockCheckedLog {
  required string block_hash = 1;
  required string state = 2;
  required string debug_message = 3;
}

// 2026-04-06T15:02:09.010720Z Saw new header hash=00000000000000000001405ace6e6e4abd39fd1e13d1b3434468ba99986b6ad5 height=943929 peer=498
// 2026-04-30T14:42:51.622131Z Saw new cmpctblock header hash=00000000000000000001f143db1e9a20f4ab523c2e9e2367d4780eae09cba1fa height=947303 peer=6709
message SawNewHeaderLog {
  required string block_hash = 1;
  required uint32 block_height = 2;
  required uint32 peer_id = 3;
  required bool is_cmpctblock = 4;
}

// 2026-04-06T15:02:09.404125Z [cmpctblock] Successfully reconstructed block 00000000000000000001405ace6e6e4abd39fd1e13d1b3434468ba99986b6ad5 with 1 txn prefilled, 2714 txn from mempool (incl at least 2 from extra pool) and 4 txn (886 bytes) requested
message CompactBlockReconstructedLog {
  required string block_hash = 1;
  required uint32 prefilled_txn_count = 2;
  required uint32 mempool_txn_count = 3;
  required uint32 extra_pool_txn_count = 4;
  required uint32 requested_txn_count = 5;
  required uint32 requested_txn_bytes = 6;
}
