{
 "title": "Anomalies (without recording rules)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "THRESHOLD_BY_COVAR", "query": "0.5" },
   { "name": "STDDEV_MULTIPLIER", "query": "2" },
   { "name": "MARGIN_MULTIPLIER", "query": "1.5" },
   { "name": "INCREASE_INTERVAL", "query": "30m" },
   { "name": "SHORT_LOOKBACK", "query": "1h" },
   { "name": "LONG_LOOKBACK", "query": "6h" },
   { "name": "HOST", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  {
   "title": "Closed connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max without(prediction_type)\r\n(\r\n  label_replace(\r\n    # margin_upper_band\r\n    avg_over_time(increase(peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m]) * $MARGIN_MULTIPLIER,\r\n    \"prediction_type\", \"margin\", \"\", \"\"\r\n  )\r\n  or\r\n  label_replace(\r\n    # upper_band_st\r\n    avg_over_time(increase(peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m])\r\n    # anomaly:adaptive:stddev_st\r\n    + avg_over_time\r\n    (\r\n      (\r\n        # anomaly:adaptive:stddev_1h:filtered\r\n        stddev_over_time(\r\n          increase\r\n          (\r\n            peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL]\r\n          )\r\n          [$SHORT_LOOKBACK:1m]\r\n        ) > avg_over_time\r\n        (\r\n          increase\r\n          (\r\n            peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL]\r\n          )\r\n          [$SHORT_LOOKBACK:1m]\r\n        )\r\n        * $THRESHOLD_BY_COVAR\r\n      )\r\n      [$LONG_LOOKBACK:1m]\r\n    )\r\n    * $STDDEV_MULTIPLIER,\r\n    \"prediction_type\", \"short_term\", \"\", \"\"\r\n  )\r\n)",
     "legendFormat": "upper_band"
    },
    {
     "expr": "clamp_min(min without(prediction_type)\r\n(\r\n  label_replace(\r\n    # margin_lower_band\r\n    avg_over_time(increase(peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m]) / $MARGIN_MULTIPLIER,\r\n    \"prediction_type\", \"margin\", \"\", \"\"\r\n  )\r\n  or\r\n  # lower_band_st\r\n  label_replace(\r\n    avg_over_time(increase(peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m])\r\n    # anomaly:adaptive:stddev_st\r\n    - avg_over_time\r\n    (\r\n      (\r\n        # anomaly:adaptive:stddev_1h:filtered\r\n        stddev_over_time\r\n        (\r\n          increase\r\n          (\r\n            peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL]\r\n          )\r\n          [$SHORT_LOOKBACK:1m]\r\n        )\r\n        > avg_over_time\r\n        (\r\n          increase\r\n          (\r\n            peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL]\r\n          )\r\n          [$SHORT_LOOKBACK:1m]\r\n        )\r\n        * $THRESHOLD_BY_COVAR\r\n      )\r\n      [$LONG_LOOKBACK:1m]\r\n    )\r\n    * $STDDEV_MULTIPLIER,\r\n    \"prediction_type\", \"short_term\", \"\", \"\"\r\n  )\r\n), 0)",
     "legendFormat": "lower_band"
    },
    {
     "expr": "(\r\n    last_over_time(\r\n      increase(peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL])\r\n      [2m:1s]\r\n    )\r\n    < bool last_over_time\r\n    (\r\n      (\r\n        clamp_min(min without(prediction_type)\r\n        (\r\n          label_replace(\r\n            # margin_lower_band\r\n            avg_over_time(increase(peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m]) / $MARGIN_MULTIPLIER,\r\n            \"prediction_type\", \"margin\", \"\", \"\"\r\n          )\r\n          or\r\n          # lower_band_st\r\n          label_replace(\r\n            avg_over_time(increase(peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m])\r\n            # anomaly:adaptive:stddev_st\r\n            - avg_over_time\r\n            (\r\n              (\r\n                # anomaly:adaptive:stddev_1h:filtered\r\n                stddev_over_time\r\n                (\r\n                  increase\r\n                  (\r\n                    peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL]\r\n                  )\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                > avg_over_time\r\n                (\r\n                  increase\r\n                  (\r\n                    peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL]\r\n                  )\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                * $THRESHOLD_BY_COVAR\r\n              )\r\n              [$LONG_LOOKBACK:1m]\r\n            )\r\n            * $STDDEV_MULTIPLIER,\r\n            \"prediction_type\", \"short_term\", \"\", \"\"\r\n          )\r\n        ), 0)\r\n      )\r\n      [2m:1s]\r\n    )\r\n)\r\n+\r\n(\r\n    last_over_time\r\n    (\r\n      increase(peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL])\r\n      [2m:1s]\r\n    )\r\n    > bool last_over_time\r\n    (\r\n      (\r\n        max without(prediction_type)\r\n        (\r\n          label_replace(\r\n            # margin_upper_band\r\n            avg_over_time(increase(peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m]) * $MARGIN_MULTIPLIER,\r\n            \"prediction_type\", \"margin\", \"\", \"\"\r\n          )\r\n          or\r\n          label_replace(\r\n            # upper_band_st\r\n            avg_over_time(increase(peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m])\r\n            # anomaly:adaptive:stddev_st\r\n            + avg_over_time\r\n            (\r\n              (\r\n                # anomaly:adaptive:stddev_1h:filtered\r\n                stddev_over_time(\r\n                  increase\r\n                  (\r\n                    peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL]\r\n                  )\r\n                  [$SHORT_LOOKBACK:1m]\r\n                ) > avg_over_time\r\n                (\r\n                  increase\r\n                  (\r\n                    peerobserver_conn_closed{host=\"$HOST\"}[$INCREASE_INTERVAL]\r\n                  )\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                * $THRESHOLD_BY_COVAR\r\n              )\r\n              [$LONG_LOOKBACK:1m]\r\n            )\r\n            * $STDDEV_MULTIPLIER,\r\n            \"prediction_type\", \"short_term\", \"\", \"\"\r\n          )\r\n        )\r\n      )\r\n      [2m:1s]\r\n    )\r\n)\r\n> bool 0",
     "legendFormat": "alert"
    }
   ]
  },
  {
   "title": "Total addresses received in Inbound addrv2 msgs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max without(prediction_type)\r\n(\r\n  label_replace(\r\n    # margin_upper_band\r\n    avg_over_time(increase(peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m]) * $MARGIN_MULTIPLIER,\r\n    \"prediction_type\", \"margin\", \"\", \"\"\r\n  )\r\n  or\r\n  label_replace(\r\n    # upper_band_st\r\n    avg_over_time(increase(peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m])\r\n    # anomaly:adaptive:stddev_st\r\n    + avg_over_time\r\n    (\r\n      (\r\n        # anomaly:adaptive:stddev_1h:filtered\r\n        stddev_over_time\r\n        (\r\n            increase\r\n            (\r\n                peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m]\r\n            )\r\n            > avg_over_time\r\n            (\r\n                increase\r\n                (\r\n                    peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL]\r\n                )\r\n                [$SHORT_LOOKBACK:1m]\r\n            )\r\n            * $THRESHOLD_BY_COVAR\r\n        )\r\n        [$LONG_LOOKBACK:1m]\r\n    )\r\n    * $STDDEV_MULTIPLIER,\r\n    \"prediction_type\", \"short_term\", \"\", \"\"\r\n  )\r\n)",
     "legendFormat": "upper_band"
    },
    {
     "expr": "clamp_min(min without(prediction_type)\r\n(\r\n  label_replace(\r\n    # margin_upper_band\r\n    avg_over_time(increase(peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m]) / $MARGIN_MULTIPLIER,\r\n    \"prediction_type\", \"margin\", \"\", \"\"\r\n  )\r\n  or\r\n  label_replace(\r\n    # upper_band_st\r\n    avg_over_time(increase(peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m])\r\n    # anomaly:adaptive:stddev_st\r\n    - avg_over_time\r\n    (\r\n      (\r\n        # anomaly:adaptive:stddev_1h:filtered\r\n        stddev_over_time\r\n        (\r\n            increase\r\n            (\r\n                peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m]\r\n            )\r\n            > avg_over_time\r\n            (\r\n                increase\r\n                (\r\n                    peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL]\r\n                )\r\n                [$SHORT_LOOKBACK:1m]\r\n            )\r\n            * $THRESHOLD_BY_COVAR\r\n        )\r\n        [$LONG_LOOKBACK:1m]\r\n    )\r\n    * $STDDEV_MULTIPLIER,\r\n    \"prediction_type\", \"short_term\", \"\", \"\"\r\n  )\r\n), 0)",
     "legendFormat": "lower_band"
    },
    {
     "expr": "(\r\n    last_over_time(\r\n      increase(peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])\r\n      [2m:1s]\r\n    )\r\n    < bool last_over_time\r\n    (\r\n      (\r\n        clamp_min(min without(prediction_type)\r\n        (\r\n          label_replace(\r\n            # margin_lower_band\r\n            avg_over_time(increase(peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m]) / $MARGIN_MULTIPLIER,\r\n            \"prediction_type\", \"margin\", \"\", \"\"\r\n          )\r\n          or\r\n          # lower_band_st\r\n          label_replace(\r\n            avg_over_time(increase(peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m])\r\n            # anomaly:adaptive:stddev_st\r\n            - avg_over_time\r\n            (\r\n              (\r\n                # anomaly:adaptive:stddev_1h:filtered\r\n                stddev_over_time\r\n                (\r\n                  increase\r\n                  (\r\n                    peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL]\r\n                  )\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                > avg_over_time\r\n                (\r\n                  increase\r\n                  (\r\n                    peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL]\r\n                  )\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                * $THRESHOLD_BY_COVAR\r\n              )\r\n              [$LONG_LOOKBACK:1m]\r\n            )\r\n            * $STDDEV_MULTIPLIER,\r\n            \"prediction_type\", \"short_term\", \"\", \"\"\r\n          )\r\n        ), 0)\r\n      )\r\n      [2m:1s]\r\n    )\r\n)\r\n+\r\n(\r\n    last_over_time\r\n    (\r\n      increase(peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])\r\n      [2m:1s]\r\n    )\r\n    > bool last_over_time\r\n    (\r\n      (\r\n        max without(prediction_type)\r\n        (\r\n          label_replace(\r\n            # margin_upper_band\r\n            avg_over_time(increase(peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m]) * $MARGIN_MULTIPLIER,\r\n            \"prediction_type\", \"margin\", \"\", \"\"\r\n          )\r\n          or\r\n          label_replace(\r\n            # upper_band_st\r\n            avg_over_time(increase(peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m])\r\n            # anomaly:adaptive:stddev_st\r\n            + avg_over_time\r\n            (\r\n              (\r\n                # anomaly:adaptive:stddev_1h:filtered\r\n                stddev_over_time(\r\n                  increase\r\n                  (\r\n                    peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL]\r\n                  )\r\n                  [$SHORT_LOOKBACK:1m]\r\n                ) > avg_over_time\r\n                (\r\n                  increase\r\n                  (\r\n                    peerobserver_p2p_addrv2_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL]\r\n                  )\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                * $THRESHOLD_BY_COVAR\r\n              )\r\n              [$LONG_LOOKBACK:1m]\r\n            )\r\n            * $STDDEV_MULTIPLIER,\r\n            \"prediction_type\", \"short_term\", \"\", \"\"\r\n          )\r\n        )\r\n      )\r\n      [2m:1s]\r\n    )\r\n)\r\n> bool 0",
     "legendFormat": "alert"
    }
   ]
  },
  {
   "title": "Total addresses received in Inbound addr msgs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max without(prediction_type)\r\n(\r\n  label_replace(\r\n    # margin_upper_band\r\n    avg_over_time(increase(peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m]) * $MARGIN_MULTIPLIER,\r\n    \"prediction_type\", \"margin\", \"\", \"\"\r\n  )\r\n  or\r\n  label_replace(\r\n    # upper_band_st\r\n    avg_over_time(increase(peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m])\r\n    # anomaly:adaptive:stddev_st\r\n    + avg_over_time\r\n    (\r\n      (\r\n        # anomaly:adaptive:stddev_1h:filtered\r\n        stddev_over_time\r\n        (\r\n            increase\r\n            (\r\n                peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m]\r\n            )\r\n            > avg_over_time\r\n            (\r\n                increase\r\n                (\r\n                    peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL]\r\n                )\r\n                [$SHORT_LOOKBACK:1m]\r\n            )\r\n            * $THRESHOLD_BY_COVAR\r\n        )\r\n        [$LONG_LOOKBACK:1m]\r\n    )\r\n    * $STDDEV_MULTIPLIER,\r\n    \"prediction_type\", \"short_term\", \"\", \"\"\r\n  )\r\n)",
     "legendFormat": "upper_band"
    },
    {
     "expr": "clamp_min(min without(prediction_type)\r\n(\r\n  label_replace(\r\n    # margin_upper_band\r\n    avg_over_time(increase(peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m]) / $MARGIN_MULTIPLIER,\r\n    \"prediction_type\", \"margin\", \"\", \"\"\r\n  )\r\n  or\r\n  label_replace(\r\n    # upper_band_st\r\n    avg_over_time(increase(peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m])\r\n    # anomaly:adaptive:stddev_st\r\n    - avg_over_time\r\n    (\r\n      (\r\n        # anomaly:adaptive:stddev_1h:filtered\r\n        stddev_over_time\r\n        (\r\n            increase\r\n            (\r\n                peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m]\r\n            )\r\n            > avg_over_time\r\n            (\r\n                increase\r\n                (\r\n                    peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL]\r\n                )\r\n                [$SHORT_LOOKBACK:1m]\r\n            )\r\n            * $THRESHOLD_BY_COVAR\r\n        )\r\n        [$LONG_LOOKBACK:1m]\r\n    )\r\n    * $STDDEV_MULTIPLIER,\r\n    \"prediction_type\", \"short_term\", \"\", \"\"\r\n  )\r\n), 0)",
     "legendFormat": "lower_band"
    },
    {
     "expr": "(\r\n    last_over_time(\r\n      increase(peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])\r\n      [2m:1s]\r\n    )\r\n    < bool last_over_time\r\n    (\r\n      (\r\n        clamp_min(min without(prediction_type)\r\n        (\r\n          label_replace(\r\n            # margin_lower_band\r\n            avg_over_time(increase(peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m]) / $MARGIN_MULTIPLIER,\r\n            \"prediction_type\", \"margin\", \"\", \"\"\r\n          )\r\n          or\r\n          # lower_band_st\r\n          label_replace(\r\n            avg_over_time(increase(peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m])\r\n            # anomaly:adaptive:stddev_st\r\n            - avg_over_time\r\n            (\r\n              (\r\n                # anomaly:adaptive:stddev_1h:filtered\r\n                stddev_over_time\r\n                (\r\n                  increase\r\n                  (\r\n                    peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL]\r\n                  )\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                > avg_over_time\r\n                (\r\n                  increase\r\n                  (\r\n                    peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL]\r\n                  )\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                * $THRESHOLD_BY_COVAR\r\n              )\r\n              [$LONG_LOOKBACK:1m]\r\n            )\r\n            * $STDDEV_MULTIPLIER,\r\n            \"prediction_type\", \"short_term\", \"\", \"\"\r\n          )\r\n        ), 0)\r\n      )\r\n      [2m:1s]\r\n    )\r\n)\r\n+\r\n(\r\n    last_over_time\r\n    (\r\n      increase(peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])\r\n      [2m:1s]\r\n    )\r\n    > bool last_over_time\r\n    (\r\n      (\r\n        max without(prediction_type)\r\n        (\r\n          label_replace(\r\n            # margin_upper_band\r\n            avg_over_time(increase(peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m]) * $MARGIN_MULTIPLIER,\r\n            \"prediction_type\", \"margin\", \"\", \"\"\r\n          )\r\n          or\r\n          label_replace(\r\n            # upper_band_st\r\n            avg_over_time(increase(peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL])[$SHORT_LOOKBACK:1m])\r\n            # anomaly:adaptive:stddev_st\r\n            + avg_over_time\r\n            (\r\n              (\r\n                # anomaly:adaptive:stddev_1h:filtered\r\n                stddev_over_time(\r\n                  increase\r\n                  (\r\n                    peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL]\r\n                  )\r\n                  [$SHORT_LOOKBACK:1m]\r\n                ) > avg_over_time\r\n                (\r\n                  increase\r\n                  (\r\n                    peerobserver_p2p_addr_addresses_sum{host=\"$HOST\", direction=\"inbound\"}[$INCREASE_INTERVAL]\r\n                  )\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                * $THRESHOLD_BY_COVAR\r\n              )\r\n              [$LONG_LOOKBACK:1m]\r\n            )\r\n            * $STDDEV_MULTIPLIER,\r\n            \"prediction_type\", \"short_term\", \"\", \"\"\r\n          )\r\n        )\r\n      )\r\n      [2m:1s]\r\n    )\r\n)\r\n> bool 0",
     "legendFormat": "alert"
    }
   ]
  },
  {
   "title": "Inbound connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "peerobserver_conn_inbound_current{host=\"$HOST\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "max without(prediction_type)\r\n(\r\n  label_replace(\r\n    # margin_upper_band\r\n    avg_over_time(peerobserver_conn_inbound_current{host=\"$HOST\"}[$SHORT_LOOKBACK:1m]) * $MARGIN_MULTIPLIER,\r\n    \"prediction_type\", \"margin\", \"\", \"\"\r\n  )\r\n  or\r\n  label_replace(\r\n    # upper_band_st\r\n    avg_over_time(peerobserver_conn_inbound_current{host=\"$HOST\"}[$SHORT_LOOKBACK:1m])\r\n    # anomaly:adaptive:stddev_st\r\n    + avg_over_time\r\n    (\r\n        (\r\n            # anomaly:adaptive:stddev_1h:filtered\r\n            stddev_over_time\r\n            (\r\n                peerobserver_conn_inbound_current{host=\"$HOST\"}[$SHORT_LOOKBACK:1m]\r\n            )\r\n            > avg_over_time\r\n            (\r\n                peerobserver_conn_inbound_current{host=\"$HOST\"}[$SHORT_LOOKBACK:1m]\r\n            )\r\n            * $THRESHOLD_BY_COVAR\r\n        )\r\n        [$LONG_LOOKBACK:1m]\r\n    )\r\n    * $STDDEV_MULTIPLIER,\r\n    \"prediction_type\", \"short_term\", \"\", \"\"\r\n  )\r\n)",
     "legendFormat": "upper_band"
    },
    {
     "expr": "clamp_min(min without(prediction_type)\r\n(\r\n  label_replace(\r\n    # margin_upper_band\r\n    avg_over_time(peerobserver_conn_inbound_current{host=\"$HOST\"}[$SHORT_LOOKBACK:1m]) / $MARGIN_MULTIPLIER,\r\n    \"prediction_type\", \"margin\", \"\", \"\"\r\n  )\r\n  or\r\n  label_replace(\r\n    # upper_band_st\r\n    avg_over_time(peerobserver_conn_inbound_current{host=\"$HOST\"}[$SHORT_LOOKBACK:1m])\r\n    # anomaly:adaptive:stddev_st\r\n    - avg_over_time\r\n    (\r\n        (\r\n            # anomaly:adaptive:stddev_1h:filtered\r\n            stddev_over_time\r\n            (\r\n                peerobserver_conn_inbound_current{host=\"$HOST\"}[$SHORT_LOOKBACK:1m]\r\n            )\r\n            > avg_over_time\r\n            (\r\n                peerobserver_conn_inbound_current{host=\"$HOST\"}[$SHORT_LOOKBACK:1m]\r\n            )\r\n            * $THRESHOLD_BY_COVAR\r\n        )\r\n        [$LONG_LOOKBACK:1m]\r\n    )\r\n    * $STDDEV_MULTIPLIER,\r\n    \"prediction_type\", \"short_term\", \"\", \"\"\r\n  )\r\n), 0)",
     "legendFormat": "lower_band"
    },
    {
     "expr": "(\r\n    last_over_time(\r\n      peerobserver_conn_inbound_current{host=\"$HOST\"}\r\n      [2m:1s]\r\n    )\r\n    < bool last_over_time\r\n    (\r\n      (\r\n        clamp_min(min without(prediction_type)\r\n        (\r\n          label_replace(\r\n            # margin_lower_band\r\n            avg_over_time(peerobserver_conn_inbound_current{host=\"$HOST\"}[$SHORT_LOOKBACK:1m]) / $MARGIN_MULTIPLIER,\r\n            \"prediction_type\", \"margin\", \"\", \"\"\r\n          )\r\n          or\r\n          # lower_band_st\r\n          label_replace(\r\n            avg_over_time(peerobserver_conn_inbound_current{host=\"$HOST\"}[$SHORT_LOOKBACK:1m])\r\n            # anomaly:adaptive:stddev_st\r\n            - avg_over_time\r\n            (\r\n              (\r\n                # anomaly:adaptive:stddev_1h:filtered\r\n                stddev_over_time\r\n                (\r\n                  peerobserver_conn_inbound_current{host=\"$HOST\"}\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                > avg_over_time\r\n                (\r\n                  peerobserver_conn_inbound_current{host=\"$HOST\"}\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                * $THRESHOLD_BY_COVAR\r\n              )\r\n              [$LONG_LOOKBACK:1m]\r\n            )\r\n            * $STDDEV_MULTIPLIER,\r\n            \"prediction_type\", \"short_term\", \"\", \"\"\r\n          )\r\n        ), 0)\r\n      )\r\n      [2m:1s]\r\n    )\r\n)\r\n+\r\n(\r\n    last_over_time\r\n    (\r\n      peerobserver_conn_inbound_current{host=\"$HOST\"}\r\n      [2m:1s]\r\n    )\r\n    > bool last_over_time\r\n    (\r\n      (\r\n        max without(prediction_type)\r\n        (\r\n          label_replace(\r\n            # margin_upper_band\r\n            avg_over_time(peerobserver_conn_inbound_current{host=\"$HOST\"}[$SHORT_LOOKBACK:1m]) * $MARGIN_MULTIPLIER,\r\n            \"prediction_type\", \"margin\", \"\", \"\"\r\n          )\r\n          or\r\n          label_replace(\r\n            # upper_band_st\r\n            avg_over_time(peerobserver_conn_inbound_current{host=\"$HOST\"}[$SHORT_LOOKBACK:1m])\r\n            # anomaly:adaptive:stddev_st\r\n            + avg_over_time\r\n            (\r\n              (\r\n                # anomaly:adaptive:stddev_1h:filtered\r\n                stddev_over_time(\r\n                  peerobserver_conn_inbound_current{host=\"$HOST\"}\r\n                  [$SHORT_LOOKBACK:1m]\r\n                ) > avg_over_time\r\n                (\r\n                  peerobserver_conn_inbound_current{host=\"$HOST\"}\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                * $THRESHOLD_BY_COVAR\r\n              )\r\n              [$LONG_LOOKBACK:1m]\r\n            )\r\n            * $STDDEV_MULTIPLIER,\r\n            \"prediction_type\", \"short_term\", \"\", \"\"\r\n          )\r\n        )\r\n      )\r\n      [2m:1s]\r\n    )\r\n)\r\n> bool 0",
     "legendFormat": "alert"
    }
   ]
  },
  {
   "title": "Peers connected via ipv4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "max without(prediction_type)\r\n(\r\n  label_replace(\r\n    # margin_upper_band\r\n    avg_over_time(peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}[$SHORT_LOOKBACK:1m]) * $MARGIN_MULTIPLIER,\r\n    \"prediction_type\", \"margin\", \"\", \"\"\r\n  )\r\n  or\r\n  label_replace(\r\n    # upper_band_st\r\n    avg_over_time(peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}[$SHORT_LOOKBACK:1m])\r\n    # anomaly:adaptive:stddev_st\r\n    + avg_over_time\r\n    (\r\n        (\r\n            # anomaly:adaptive:stddev_1h:filtered\r\n            stddev_over_time\r\n            (\r\n                peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}[$SHORT_LOOKBACK:1m]\r\n            )\r\n            > avg_over_time\r\n            (\r\n                peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}[$SHORT_LOOKBACK:1m]\r\n            )\r\n            * $THRESHOLD_BY_COVAR\r\n        )\r\n        [$LONG_LOOKBACK:1m]\r\n    )\r\n    * $STDDEV_MULTIPLIER,\r\n    \"prediction_type\", \"short_term\", \"\", \"\"\r\n  )\r\n)",
     "legendFormat": "upper_band"
    },
    {
     "expr": "clamp_min(min without(prediction_type)\r\n(\r\n  label_replace(\r\n    # margin_upper_band\r\n    avg_over_time(peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}[$SHORT_LOOKBACK:1m]) / $MARGIN_MULTIPLIER,\r\n    \"prediction_type\", \"margin\", \"\", \"\"\r\n  )\r\n  or\r\n  label_replace(\r\n    # upper_band_st\r\n    avg_over_time(peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}[$SHORT_LOOKBACK:1m])\r\n    # anomaly:adaptive:stddev_st\r\n    - avg_over_time\r\n    (\r\n        (\r\n            # anomaly:adaptive:stddev_1h:filtered\r\n            stddev_over_time\r\n            (\r\n                peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}[$SHORT_LOOKBACK:1m]\r\n            )\r\n            > avg_over_time\r\n            (\r\n                peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}[$SHORT_LOOKBACK:1m]\r\n            )\r\n            * $THRESHOLD_BY_COVAR\r\n        )\r\n        [$LONG_LOOKBACK:1m]\r\n    )\r\n    * $STDDEV_MULTIPLIER,\r\n    \"prediction_type\", \"short_term\", \"\", \"\"\r\n  )\r\n), 0)",
     "legendFormat": "lower_band"
    },
    {
     "expr": "(\r\n    last_over_time(\r\n      peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}\r\n      [2m:1s]\r\n    )\r\n    < bool last_over_time\r\n    (\r\n      (\r\n        clamp_min(min without(prediction_type)\r\n        (\r\n          label_replace(\r\n            # margin_lower_band\r\n            avg_over_time(peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}[$SHORT_LOOKBACK:1m]) / $MARGIN_MULTIPLIER,\r\n            \"prediction_type\", \"margin\", \"\", \"\"\r\n          )\r\n          or\r\n          # lower_band_st\r\n          label_replace(\r\n            avg_over_time(peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}[$SHORT_LOOKBACK:1m])\r\n            # anomaly:adaptive:stddev_st\r\n            - avg_over_time\r\n            (\r\n              (\r\n                # anomaly:adaptive:stddev_1h:filtered\r\n                stddev_over_time\r\n                (\r\n                  peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                > avg_over_time\r\n                (\r\n                  peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                * $THRESHOLD_BY_COVAR\r\n              )\r\n              [$LONG_LOOKBACK:1m]\r\n            )\r\n            * $STDDEV_MULTIPLIER,\r\n            \"prediction_type\", \"short_term\", \"\", \"\"\r\n          )\r\n        ), 0)\r\n      )\r\n      [2m:1s]\r\n    )\r\n)\r\n+\r\n(\r\n    last_over_time\r\n    (\r\n      peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}\r\n      [2m:1s]\r\n    )\r\n    > bool last_over_time\r\n    (\r\n      (\r\n        max without(prediction_type)\r\n        (\r\n          label_replace(\r\n            # margin_upper_band\r\n            avg_over_time(peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}[$SHORT_LOOKBACK:1m]) * $MARGIN_MULTIPLIER,\r\n            \"prediction_type\", \"margin\", \"\", \"\"\r\n          )\r\n          or\r\n          label_replace(\r\n            # upper_band_st\r\n            avg_over_time(peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}[$SHORT_LOOKBACK:1m])\r\n            # anomaly:adaptive:stddev_st\r\n            + avg_over_time\r\n            (\r\n              (\r\n                # anomaly:adaptive:stddev_1h:filtered\r\n                stddev_over_time(\r\n                  peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}\r\n                  [$SHORT_LOOKBACK:1m]\r\n                ) > avg_over_time\r\n                (\r\n                  peerobserver_rpc_peer_info_network_peers{host=\"$HOST\", network=\"ipv4\"}\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                * $THRESHOLD_BY_COVAR\r\n              )\r\n              [$LONG_LOOKBACK:1m]\r\n            )\r\n            * $STDDEV_MULTIPLIER,\r\n            \"prediction_type\", \"short_term\", \"\", \"\"\r\n          )\r\n        )\r\n      )\r\n      [2m:1s]\r\n    )\r\n)\r\n> bool 0",
     "legendFormat": "alert"
    }
   ]
  },
  {
   "title": "Outbound traffic share to LinkingLion peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum( increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]) ) / sum ( increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]) )",
     "legendFormat": "__auto"
    },
    {
     "expr": "max without(prediction_type)\r\n(\r\n  label_replace(\r\n    # margin_lower_band\r\n    avg_over_time\r\n    (\r\n        # peerobserver_p2p_share_linkinglion_total\r\n        (\r\n            sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n            / sum (increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n        )\r\n        [$SHORT_LOOKBACK:1m]\r\n    ) * $MARGIN_MULTIPLIER,\r\n    \"prediction_type\", \"margin\", \"\", \"\"\r\n  )\r\n  or\r\n  # lower_band_st\r\n  label_replace(\r\n    avg_over_time(\r\n      # peerobserver_p2p_share_linkinglion_total\r\n      (\r\n          sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n          / sum (increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n      )\r\n      [$SHORT_LOOKBACK:1m]\r\n    )\r\n    # anomaly:adaptive:stddev_st\r\n    + avg_over_time\r\n    (\r\n      (\r\n        # anomaly:adaptive:stddev_1h:filtered\r\n        stddev_over_time\r\n        (\r\n            # peerobserver_p2p_share_linkinglion_total\r\n            (\r\n                sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n                / sum (increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n            )\r\n            [$SHORT_LOOKBACK:1m]\r\n        )\r\n        > avg_over_time\r\n        (\r\n            # peerobserver_p2p_share_linkinglion_total\r\n            (\r\n                sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n                / sum ( increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n            ) \r\n            [$SHORT_LOOKBACK:1m]\r\n        )\r\n        * $THRESHOLD_BY_COVAR\r\n      )\r\n      [$LONG_LOOKBACK:1m]\r\n    )\r\n    * $STDDEV_MULTIPLIER,\r\n    \"prediction_type\", \"short_term\", \"\", \"\"\r\n  )\r\n)",
     "legendFormat": "upper_band"
    },
    {
     "expr": "clamp_min(min without(prediction_type)\r\n(\r\n  label_replace(\r\n    # margin_lower_band\r\n    avg_over_time\r\n    (\r\n        # peerobserver_p2p_share_linkinglion_total\r\n        (\r\n            sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n            / sum (increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n        )\r\n        [$SHORT_LOOKBACK:1m]\r\n    ) / $MARGIN_MULTIPLIER,\r\n    \"prediction_type\", \"margin\", \"\", \"\"\r\n  )\r\n  or\r\n  # lower_band_st\r\n  label_replace(\r\n    avg_over_time(\r\n      # peerobserver_p2p_share_linkinglion_total\r\n      (\r\n          sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n          / sum (increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n      )\r\n      [$SHORT_LOOKBACK:1m]\r\n    )\r\n    # anomaly:adaptive:stddev_st\r\n    - avg_over_time\r\n    (\r\n      (\r\n        # anomaly:adaptive:stddev_1h:filtered\r\n        stddev_over_time\r\n        (\r\n            # peerobserver_p2p_share_linkinglion_total\r\n            (\r\n                sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n                / sum (increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n            )\r\n            [$SHORT_LOOKBACK:1m]\r\n        )\r\n        > avg_over_time\r\n        (\r\n            # peerobserver_p2p_share_linkinglion_total\r\n            (\r\n                sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n                / sum ( increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n            ) \r\n            [$SHORT_LOOKBACK:1m]\r\n        )\r\n        * $THRESHOLD_BY_COVAR\r\n      )\r\n      [$LONG_LOOKBACK:1m]\r\n    )\r\n    * $STDDEV_MULTIPLIER,\r\n    \"prediction_type\", \"short_term\", \"\", \"\"\r\n  )\r\n), 0)",
     "legendFormat": "lower_band"
    },
    {
     "expr": "(\r\n    last_over_time(\r\n      # peerobserver_p2p_share_linkinglion_total\r\n      (\r\n          sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n          / sum (increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n      )\r\n      [2m:1s]\r\n    )\r\n    < bool last_over_time\r\n    (\r\n      (\r\n        clamp_min(min without(prediction_type)\r\n        (\r\n          label_replace(\r\n            # margin_lower_band\r\n            avg_over_time(\r\n              # peerobserver_p2p_share_linkinglion_total\r\n              (\r\n                sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n                / sum (increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n              )\r\n              [$SHORT_LOOKBACK:1m]\r\n            ) / $MARGIN_MULTIPLIER,\r\n            \"prediction_type\", \"margin\", \"\", \"\"\r\n          )\r\n          or\r\n          # lower_band_st\r\n          label_replace(\r\n            avg_over_time(\r\n              # peerobserver_p2p_share_linkinglion_total\r\n              (\r\n                sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n                / sum (increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n              )\r\n              [$SHORT_LOOKBACK:1m]\r\n            )\r\n            # anomaly:adaptive:stddev_st\r\n            - avg_over_time\r\n            (\r\n              (\r\n                # anomaly:adaptive:stddev_1h:filtered\r\n                stddev_over_time\r\n                (\r\n                  # peerobserver_p2p_share_linkinglion_total\r\n                  (\r\n                    sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n                    / sum (increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n                  )\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                > avg_over_time\r\n                (\r\n                  # peerobserver_p2p_share_linkinglion_total\r\n                  (\r\n                    sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n                    / sum (increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n                  )\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                * $THRESHOLD_BY_COVAR\r\n              )\r\n              [$LONG_LOOKBACK:1m]\r\n            )\r\n            * $STDDEV_MULTIPLIER,\r\n            \"prediction_type\", \"short_term\", \"\", \"\"\r\n          )\r\n        ), 0)\r\n      )\r\n      [2m:1s]\r\n    )\r\n)\r\n+\r\n(\r\n    last_over_time\r\n    (\r\n      # peerobserver_p2p_share_linkinglion_total\r\n      (\r\n          sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n          / sum (increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n      )\r\n      [2m:1s]\r\n    )\r\n    > bool last_over_time\r\n    (\r\n      (\r\n        max without(prediction_type)\r\n        (\r\n          label_replace(\r\n            # margin_upper_band\r\n            avg_over_time(\r\n              # peerobserver_p2p_share_linkinglion_total\r\n              (\r\n                sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n                / sum (increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n              )\r\n              [$SHORT_LOOKBACK:1m]\r\n            ) * $MARGIN_MULTIPLIER,\r\n            \"prediction_type\", \"margin\", \"\", \"\"\r\n          )\r\n          or\r\n          label_replace(\r\n            # upper_band_st\r\n            avg_over_time(\r\n              # peerobserver_p2p_share_linkinglion_total\r\n              (\r\n                sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n                / sum (increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n              )\r\n              [$SHORT_LOOKBACK:1m]\r\n            )\r\n            # anomaly:adaptive:stddev_st\r\n            + avg_over_time\r\n            (\r\n              (\r\n                # anomaly:adaptive:stddev_1h:filtered\r\n                stddev_over_time(\r\n                  # peerobserver_p2p_share_linkinglion_total\r\n                  (\r\n                    sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n                    / sum (increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n                  )\r\n                  [$SHORT_LOOKBACK:1m]\r\n                ) > avg_over_time\r\n                (\r\n                  # peerobserver_p2p_share_linkinglion_total\r\n                  (\r\n                    sum(increase(peerobserver_p2p_message_bytes_linkinglion{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n                    / sum (increase(peerobserver_p2p_message_bytes{host=\"$HOST\", direction=\"outbound\"}[$INCREASE_INTERVAL]))\r\n                  )\r\n                  [$SHORT_LOOKBACK:1m]\r\n                )\r\n                * $THRESHOLD_BY_COVAR\r\n              )\r\n              [$LONG_LOOKBACK:1m]\r\n            )\r\n            * $STDDEV_MULTIPLIER,\r\n            \"prediction_type\", \"short_term\", \"\", \"\"\r\n          )\r\n        )\r\n      )\r\n      [2m:1s]\r\n    )\r\n)\r\n> bool 0",
     "legendFormat": "alert"
    }
   ]
  }
 ]
}