{
 "title": "[fees] Fee Rate Estimates",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "1 block Conservative (sat/vB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "peerobserver_rpc_estimatesmartfee_feerate{target_block=\"1\", mode=\"CONSERVATIVE\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "6 blocks Conservative (sat/vB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "peerobserver_rpc_estimatesmartfee_feerate{target_block=\"6\", mode=\"CONSERVATIVE\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "144 blocks Conservative (sat/vB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "peerobserver_rpc_estimatesmartfee_feerate{target_block=\"144\", mode=\"CONSERVATIVE\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "1 block Economical (sat/vB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "peerobserver_rpc_estimatesmartfee_feerate{target_block=\"1\", mode=\"ECONOMICAL\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "6 blocks Economical (sat/vB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "peerobserver_rpc_estimatesmartfee_feerate{target_block=\"6\", mode=\"ECONOMICAL\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "144 blocks Economical (sat/vB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "peerobserver_rpc_estimatesmartfee_feerate{target_block=\"144\", mode=\"ECONOMICAL\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}