{
 "title": "Logs",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "category",
    "label": "category",
    "query": {
     "query": "label_values(peerobserver_log_events,category)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Logs by log-level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs by level (1min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(level, host) (increase(peerobserver_log_events[1m]))",
     "legendFormat": "{{host}}-{{level}}"
    }
   ]
  },
  {
   "title": "Log bytes by level (1min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(level, host) (increase(peerobserver_log_bytes[1m]))",
     "legendFormat": "{{host}}-{{level}}"
    }
   ]
  },
  { "title": "Logs by category", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Debug log lines with \"$category\" category\" (per 1min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "repeat": "category",
   "targets": [
    {
     "expr": "increase(peerobserver_log_events{category=\"$category\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Debug log bytes with \"$category\" category",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "repeat": "category",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "increase(peerobserver_log_bytes{category=\"$category\"}[1m]) / 60",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Mutated blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Mutated blocks (all time)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "sum by(host, status) (peerobserver_log_mutated_blocks)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mutated blocks (1min)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "sum by(host, status) (increase(peerobserver_log_mutated_blocks[1m]))",
     "legendFormat": "{{host}} {{status}}"
    }
   ]
  }
 ]
}